name: Report de bug
description: Formulaire de report de bug
title: "[Bug]"
labels: ["bug", "triage"]
assignees:
  - amitron-dev
body:
  - type: markdown
    attributes:
      value: |
        Merci de remplir se formulaire !
  - type: textarea
    id: why
    attributes:
      label: Que c est t-il passé ?
      value: "Explique ce qu'il c'est passé ?"
    validations:
      required: true
  - type: textarea
    id: devraissepassé
    attributes:
      label: Que devrais t-il se passé ?
      value: "Explique se qu'il devrais se passé ?"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: Avez - vous une version de launcher personnalisée ?
      options:
        - Non
        - Oui
      default: 0
    validations:
      required: false
