name: Questions
description: Pose nous une question sur le plugin.
assignees: Amitron-Dev
labels: "QUESTION"
title: "[QUESTION] "
body:
- type: dropdown
  id: read
  attributes:
    label: Avez - vous lu le wiki ?
    options:
      - Oui
      - Non
  validations:
    required: true
- type: textarea
  id: question
  attributes:
    label: Pose nous ta question.
  validations:
    required: true
