name: Questions
description: Pose nous une question sur le plugin.
assignees: Amitron-Dev
labels: "QUESTION"
title: "[QUESTION] "
body:
- type: checkboxes
  id: read
  attributes:
    label: A-tu lu le wiki ?
    options:
      - label: Oui
      - label: Non
  validations:
    required: true
- type: textarea
  id: question
  attributes:
    label: Pose nous ta question.
  validations:
    required: true
